"""Phase 2 schema: analytics, opportunity, portfolio, evaluation, journal

Revision ID: 73f7305b958a
Revises: 0001_initial
Create Date: 2026-08-07 15:01:46.992283+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from tradeit.storage.tables import UTCDateTime

revision: str = "0002_phase2_schema"
down_revision: str | None = '0001_initial'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ---------------------------------------------------------------------------
# Partitioning
#
# A partitioned table with no partitions rejects every insert, so the initial
# set is created here and a helper function lets the weekly maintenance job
# extend it. Partitions are created well ahead of need: discovering a missing
# partition at ingest time means a failed load, and the cost of an empty
# partition is negligible.
#
# The DEFAULT partition is a safety net, not a destination. Rows landing there
# mean the maintenance job fell behind. It must be kept empty, because
# PostgreSQL refuses to attach a new partition whose range overlaps rows
# already sitting in the default.
# ---------------------------------------------------------------------------

CREATE_PARTITION_HELPER = """
CREATE OR REPLACE FUNCTION tradeit_ensure_month_partition(
    parent regclass,
    month_start date
) RETURNS void
LANGUAGE plpgsql
AS $$
DECLARE
    child_name text;
    next_month date := (month_start + interval '1 month')::date;
BEGIN
    child_name := format('%s_p%s', parent::text, to_char(month_start, 'YYYYMM'));
    IF to_regclass(child_name) IS NULL THEN
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF %s FOR VALUES FROM (%L) TO (%L)',
            child_name, parent::text, month_start, next_month
        );
    END IF;
END;
$$;
"""

PARTITIONED_TABLES = ("indicator_values", "system_logs")


def _create_initial_partitions() -> None:
    op.execute(CREATE_PARTITION_HELPER)
    for table in PARTITIONED_TABLES:
        op.execute(
            f"CREATE TABLE {table}_default PARTITION OF {table} DEFAULT"
        )
        # Twenty-six months: the trailing two years a fresh install backfills,
        # plus two months of runway before the maintenance job must extend it.
        op.execute(
            f"""
            DO $$
            DECLARE m date;
            BEGIN
                FOR m IN
                    SELECT generate_series(
                        date_trunc('month', CURRENT_DATE - interval '24 months'),
                        date_trunc('month', CURRENT_DATE + interval '2 months'),
                        interval '1 month'
                    )::date
                LOOP
                    PERFORM tradeit_ensure_month_partition('{table}'::regclass, m);
                END LOOP;
            END $$;
            """
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifact_versions',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index('ix_artifact_kind_name', 'artifact_versions', ['kind', 'name', 'created_at'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('check_name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('blocks_trading', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('check_name', 'dataset', 'instrument_id', 'session_date', name='uq_quality_issue')
    )
    op.create_index('ix_quality_blocking', 'data_quality_issues', ['blocks_trading', 'resolved_at'], unique=False)
    op.create_index('ix_quality_open', 'data_quality_issues', ['detected_on', 'severity', 'resolved_at'], unique=False)
    op.create_table('data_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('dataset', sa.String(length=64), nullable=False),
    sa.Column('max_ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest', 'dataset', name='uq_snapshot_dataset')
    )
    op.create_index('ix_snapshot_digest', 'data_snapshots', ['digest'], unique=False)
    op.create_table('indicator_values',
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('indicator', sa.String(length=48), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('feature_set_digest', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('is_warm', sa.Boolean(), nullable=False),
    sa.Column('computed_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('instrument_id', 'session_date', 'indicator', 'timeframe', 'feature_set_digest'),
    postgresql_partition_by='RANGE (session_date)'
    )
    op.create_index('ix_indicator_lookup', 'indicator_values', ['instrument_id', 'indicator', 'session_date'], unique=False)
    op.create_index('ix_indicator_session', 'indicator_values', ['session_date', 'indicator'], unique=False)
    op.create_table('job_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('rows_processed', sa.BigInteger(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name', 'session_date', 'attempt', name='uq_job_attempt')
    )
    op.create_index('ix_job_recent', 'job_runs', ['job_name', 'started_at'], unique=False)
    op.create_index('ix_job_session_status', 'job_runs', ['session_date', 'status'], unique=False)
    op.create_table('macro_observations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('event_time', UTCDateTime(timezone=True), nullable=False),
    sa.Column('knowledge_time', UTCDateTime(timezone=True), nullable=False),
    sa.Column('knowledge_source', sa.String(length=16), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('vintage', sa.Integer(), nullable=False),
    sa.Column('ingested_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'period_end', 'vintage', name='uq_macro_vintage')
    )
    op.create_index('ix_macro_pit', 'macro_observations', ['series_id', 'knowledge_time'], unique=False)
    op.create_table('sector_strength',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('scheme', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('relative_strength', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('pct_above_200ma', sa.Float(), nullable=True),
    sa.Column('feature_set_digest', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date', 'scheme', 'sector', 'feature_set_digest', name='uq_sector_strength')
    )
    op.create_index('ix_sector_strength_session', 'sector_strength', ['session_date', 'rank'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_logs',
    sa.Column('logged_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('event', sa.String(length=96), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger(), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('logged_at', 'event_id'),
    postgresql_partition_by='RANGE (logged_at)'
    )
    op.create_index('ix_syslog_category', 'system_logs', ['category', 'logged_at'], unique=False)
    op.create_index('ix_syslog_time', 'system_logs', ['logged_at', 'level'], unique=False)
    op.create_table('market_regime_states',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('classifier', sa.String(length=48), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('benchmark_instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('strategy_config_digest', sa.String(length=64), nullable=False),
    sa.Column('computed_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_instrument_id'], ['instruments.instrument_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_date', 'classifier', 'strategy_config_digest', name='uq_regime_state')
    )
    op.create_index('ix_regime_session', 'market_regime_states', ['session_date'], unique=False)
    op.create_table('model_metadata',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('model_type', sa.String(length=48), nullable=False),
    sa.Column('framework', sa.String(length=48), nullable=True),
    sa.Column('training_start', sa.Date(), nullable=True),
    sa.Column('training_end', sa.Date(), nullable=True),
    sa.Column('validation_start', sa.Date(), nullable=True),
    sa.Column('validation_end', sa.Date(), nullable=True),
    sa.Column('feature_set_digest', sa.String(length=64), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('training_end IS NULL OR training_start IS NULL OR training_end > training_start', name='ck_model_training_window'),
    sa.CheckConstraint('validation_start IS NULL OR training_end IS NULL OR validation_start >= training_end', name='ck_model_validation_after_training'),
    sa.ForeignKeyConstraint(['digest'], ['artifact_versions.digest'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('digest')
    )
    op.create_index('ix_model_name', 'model_metadata', ['name', 'created_at'], unique=False)
    op.create_table('news_items',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('event_time', UTCDateTime(timezone=True), nullable=False),
    sa.Column('knowledge_time', UTCDateTime(timezone=True), nullable=False),
    sa.Column('knowledge_source', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('sentiment_model_version', sa.String(length=64), nullable=True),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('ingested_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint('sentiment IS NULL OR sentiment_model_version IS NOT NULL', name='ck_news_sentiment_provenance'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id', 'knowledge_time', name='uq_news_external')
    )
    op.create_index('ix_news_pit', 'news_items', ['instrument_id', 'knowledge_time'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=False),
    sa.Column('broker_account_ref', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('backtest', 'paper', 'live')", name='ck_portfolio_mode'),
    sa.CheckConstraint('initial_capital > 0', name='ck_portfolio_capital'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('run_manifests',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('run_kind', sa.String(length=24), nullable=False),
    sa.Column('as_of', UTCDateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('manifest_digest', sa.String(length=64), nullable=False),
    sa.Column('strategy_config_digest', sa.String(length=64), nullable=False),
    sa.Column('data_snapshot_digest', sa.String(length=64), nullable=False),
    sa.Column('feature_set_digest', sa.String(length=64), nullable=True),
    sa.Column('model_digest', sa.String(length=64), nullable=True),
    sa.Column('code_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_snapshot_digest'], ['artifact_versions.digest'], ),
    sa.ForeignKeyConstraint(['feature_set_digest'], ['artifact_versions.digest'], ),
    sa.ForeignKeyConstraint(['model_digest'], ['artifact_versions.digest'], ),
    sa.ForeignKeyConstraint(['strategy_config_digest'], ['artifact_versions.digest'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_index('ix_manifest_asof', 'run_manifests', ['run_kind', 'as_of'], unique=False)
    op.create_index('ix_manifest_digest', 'run_manifests', ['manifest_digest'], unique=False)
    op.create_index('ix_manifest_session', 'run_manifests', ['session_date', 'run_kind'], unique=False)
    op.create_table('sectors',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('scheme', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=96), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('ingested_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_sector_interval'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sector_asof', 'sectors', ['instrument_id', 'scheme', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_sector_lookup', 'sectors', ['scheme', 'sector', 'valid_from'], unique=False)
    op.create_table('strategy_configurations',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('activated_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('deactivated_at IS NULL OR activated_at IS NULL OR deactivated_at > activated_at', name='ck_strategy_config_interval'),
    sa.ForeignKeyConstraint(['digest'], ['artifact_versions.digest'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'digest', name='uq_strategy_config')
    )
    op.create_index('ix_strategy_config_active', 'strategy_configurations', ['strategy_id', 'activated_at', 'deactivated_at'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('strategy_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('universe', sa.String(length=64), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('cost_model', sa.String(length=48), nullable=False),
    sa.Column('fill_model', sa.String(length=48), nullable=False),
    sa.Column('walk_forward_window', sa.Integer(), nullable=True),
    sa.Column('is_out_of_sample', sa.Boolean(), nullable=False),
    sa.Column('total_return_pct', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('max_drawdown_pct', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('sortino', sa.Float(), nullable=True),
    sa.Column('calmar', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('expectancy_r', sa.Float(), nullable=True),
    sa.Column('trade_count', sa.Integer(), nullable=False),
    sa.Column('exposure_pct', sa.Float(), nullable=True),
    sa.Column('benchmark_return_pct', sa.Float(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('equity_curve', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('data_caveats', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('started_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date > start_date', name='ck_backtest_dates'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_status', 'backtest_runs', ['status', 'created_at'], unique=False)
    op.create_index('ix_backtest_strategy', 'backtest_runs', ['strategy_id', 'created_at'], unique=False)
    op.create_table('patterns',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pattern_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('last_evaluated_on', sa.Date(), nullable=False),
    sa.Column('pivot_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('depth_pct', sa.Float(), nullable=True),
    sa.Column('length_sessions', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Float(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_pattern_dates'),
    sa.CheckConstraint('quality >= 0 AND quality <= 1', name='ck_pattern_quality'),
    sa.CheckConstraint('stop_price IS NULL OR pivot_price IS NULL OR stop_price < pivot_price', name='ck_pattern_stop_below_pivot'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'pattern_type', 'start_date', 'detected_on', name='uq_pattern')
    )
    op.create_index('ix_pattern_active', 'patterns', ['status', 'last_evaluated_on'], unique=False)
    op.create_index('ix_pattern_instrument', 'patterns', ['instrument_id', 'detected_on'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('as_of', UTCDateTime(timezone=True), nullable=False),
    sa.Column('cash', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('equity', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('long_market_value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('short_market_value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('realised_pnl_to_date', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('unrealised_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('drawdown_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'session_date', name='uq_portfolio_snapshot')
    )
    op.create_index('ix_snapshot_curve', 'portfolio_snapshots', ['portfolio_id', 'session_date'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('as_of', UTCDateTime(timezone=True), nullable=False),
    sa.Column('equity', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('open_risk', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('heat_pct', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('largest_position_pct', sa.Float(), nullable=True),
    sa.Column('gross_exposure_pct', sa.Float(), nullable=True),
    sa.Column('max_pairwise_correlation', sa.Float(), nullable=True),
    sa.Column('drawdown_from_peak_pct', sa.Float(), nullable=True),
    sa.Column('sector_exposures', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('limit_breaches', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('strategy_config_digest', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'session_date', name='uq_risk_snapshot')
    )
    op.create_index('ix_risk_snapshot_breach', 'risk_snapshots', ['portfolio_id', 'session_date'], unique=False)
    op.create_table('screen_rejections',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('filter_name', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('measured_value', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rejection_filter', 'screen_rejections', ['run_manifest_id', 'filter_name'], unique=False)
    op.create_index('ix_rejection_lookup', 'screen_rejections', ['session_date', 'instrument_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'session_date', name='uq_watchlist_day')
    )
    op.create_index('ix_watchlist_session', 'watchlists', ['session_date'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('costs', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('holding_sessions', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('mfe', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('score_at_entry', sa.Float(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=24), nullable=True),
    sa.Column('sector_at_entry', sa.String(length=64), nullable=True),
    sa.CheckConstraint('exit_date >= entry_date', name='ck_backtest_trade_dates'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backtest_trade_attr', 'backtest_trades', ['backtest_run_id', 'exit_reason'], unique=False)
    op.create_index('ix_backtest_trade_run', 'backtest_trades', ['backtest_run_id', 'exit_date'], unique=False)
    op.create_table('breakout_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('pattern_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pivot_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('distance_to_pivot_pct', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('follow_through_pct', sa.Float(), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'pattern_id', 'session_date', 'status', name='uq_breakout_event')
    )
    op.create_index('ix_breakout_pattern', 'breakout_events', ['pattern_id', 'session_date'], unique=False)
    op.create_index('ix_breakout_session', 'breakout_events', ['session_date', 'status'], unique=False)
    op.create_table('monte_carlo_runs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('backtest_run_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('return_percentiles', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('drawdown_percentiles', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('ruin_probability', sa.Float(), nullable=True),
    sa.Column('iterations_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('iterations >= 100', name='ck_montecarlo_iterations'),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_montecarlo_backtest', 'monte_carlo_runs', ['backtest_run_id', 'method'], unique=False)
    op.create_table('opportunity_scores',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('pattern_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('breakout_event_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.CheckConstraint('total >= 0 AND total <= 1', name='ck_score_range'),
    sa.ForeignKeyConstraint(['breakout_event_id'], ['breakout_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pattern_id'], ['patterns.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_id', 'session_date', 'run_manifest_id', name='uq_score_per_run')
    )
    op.create_index('ix_score_instrument', 'opportunity_scores', ['instrument_id', 'session_date'], unique=False)
    op.create_index('ix_score_ranking', 'opportunity_scores', ['session_date', 'total'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('initial_stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('initial_risk_amount', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=False),
    sa.Column('closed_on', sa.Date(), nullable=True),
    sa.Column('realised_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('pyramid_entries', sa.Integer(), nullable=False),
    sa.Column('entry_score_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('entry_run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.CheckConstraint("status <> 'open' OR stop_price IS NOT NULL", name='ck_position_open_has_stop'),
    sa.CheckConstraint('closed_on IS NULL OR closed_on >= opened_on', name='ck_position_dates'),
    sa.CheckConstraint('quantity >= 0', name='ck_position_quantity'),
    sa.ForeignKeyConstraint(['entry_run_manifest_id'], ['run_manifests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['entry_score_id'], ['opportunity_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_position_instrument', 'positions', ['portfolio_id', 'instrument_id', 'opened_on'], unique=False)
    op.create_index('ix_position_open', 'positions', ['portfolio_id', 'status'], unique=False)
    op.create_table('watchlist_members',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('score_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('trigger_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['score_id'], ['opportunity_scores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name='uq_watchlist_member')
    )
    op.create_index('ix_watchlist_member_rank', 'watchlist_members', ['watchlist_id', 'rank'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('instrument_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('client_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('time_in_force', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('intent', sa.String(length=128), nullable=True),
    sa.Column('submitted_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('completed_at', UTCDateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('filled_quantity >= 0 AND filled_quantity <= quantity', name='ck_order_filled'),
    sa.CheckConstraint('quantity > 0', name='ck_order_quantity'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_order_id')
    )
    op.create_index('ix_order_broker', 'orders', ['broker_order_id'], unique=False)
    op.create_index('ix_order_portfolio', 'orders', ['portfolio_id', 'created_at'], unique=False)
    op.create_index('ix_order_status', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('position_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('exit_reason', sa.String(length=32), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('costs', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('holding_sessions', sa.Integer(), nullable=False),
    sa.Column('mae', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('mfe', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('score_at_entry', sa.Float(), nullable=True),
    sa.Column('regime_at_entry', sa.String(length=24), nullable=True),
    sa.Column('sector_at_entry', sa.String(length=64), nullable=True),
    sa.CheckConstraint('exit_date >= entry_date', name='ck_trade_dates'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('position_id', name='uq_trade_position')
    )
    op.create_index('ix_trade_analysis', 'trades', ['portfolio_id', 'exit_reason', 'exit_date'], unique=False)
    op.create_index('ix_trade_portfolio', 'trades', ['portfolio_id', 'exit_date'], unique=False)
    op.create_table('executions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('instrument_id', sa.BigInteger(), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('commission', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('filled_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=True),
    sa.Column('broker_execution_id', sa.String(length=64), nullable=True),
    sa.CheckConstraint('quantity > 0 AND price > 0', name='ck_execution_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_execution_id', name='uq_execution_broker')
    )
    op.create_index('ix_execution_order', 'executions', ['order_id'], unique=False)
    op.create_index('ix_execution_portfolio', 'executions', ['portfolio_id', 'session_date'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('position_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('trade_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('instrument_id', sa.BigInteger(), nullable=True),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('occurred_at', UTCDateTime(timezone=True), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('run_manifest_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('author', sa.String(length=64), nullable=False),
    sa.Column('created_at', UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_manifest_id'], ['run_manifests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_journal_portfolio', 'journal_entries', ['portfolio_id', 'session_date'], unique=False)
    op.create_index('ix_journal_position', 'journal_entries', ['position_id', 'occurred_at'], unique=False)
    op.create_index('ix_journal_type', 'journal_entries', ['entry_type', 'session_date'], unique=False)
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        _create_initial_partitions()


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        op.execute("DROP FUNCTION IF EXISTS tradeit_ensure_month_partition(regclass, date)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_journal_type', table_name='journal_entries')
    op.drop_index('ix_journal_position', table_name='journal_entries')
    op.drop_index('ix_journal_portfolio', table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index('ix_execution_portfolio', table_name='executions')
    op.drop_index('ix_execution_order', table_name='executions')
    op.drop_table('executions')
    op.drop_index('ix_trade_portfolio', table_name='trades')
    op.drop_index('ix_trade_analysis', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_order_status', table_name='orders')
    op.drop_index('ix_order_portfolio', table_name='orders')
    op.drop_index('ix_order_broker', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_watchlist_member_rank', table_name='watchlist_members')
    op.drop_table('watchlist_members')
    op.drop_index('ix_position_open', table_name='positions')
    op.drop_index('ix_position_instrument', table_name='positions')
    op.drop_table('positions')
    op.drop_index('ix_score_ranking', table_name='opportunity_scores')
    op.drop_index('ix_score_instrument', table_name='opportunity_scores')
    op.drop_table('opportunity_scores')
    op.drop_index('ix_montecarlo_backtest', table_name='monte_carlo_runs')
    op.drop_table('monte_carlo_runs')
    op.drop_index('ix_breakout_session', table_name='breakout_events')
    op.drop_index('ix_breakout_pattern', table_name='breakout_events')
    op.drop_table('breakout_events')
    op.drop_index('ix_backtest_trade_run', table_name='backtest_trades')
    op.drop_index('ix_backtest_trade_attr', table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index('ix_watchlist_session', table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index('ix_rejection_lookup', table_name='screen_rejections')
    op.drop_index('ix_rejection_filter', table_name='screen_rejections')
    op.drop_table('screen_rejections')
    op.drop_index('ix_risk_snapshot_breach', table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index('ix_snapshot_curve', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_pattern_instrument', table_name='patterns')
    op.drop_index('ix_pattern_active', table_name='patterns')
    op.drop_table('patterns')
    op.drop_index('ix_backtest_strategy', table_name='backtest_runs')
    op.drop_index('ix_backtest_status', table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index('ix_strategy_config_active', table_name='strategy_configurations')
    op.drop_table('strategy_configurations')
    op.drop_index('ix_sector_lookup', table_name='sectors')
    op.drop_index('ix_sector_asof', table_name='sectors')
    op.drop_table('sectors')
    op.drop_index('ix_manifest_session', table_name='run_manifests')
    op.drop_index('ix_manifest_digest', table_name='run_manifests')
    op.drop_index('ix_manifest_asof', table_name='run_manifests')
    op.drop_table('run_manifests')
    op.drop_table('portfolios')
    op.drop_index('ix_news_pit', table_name='news_items')
    op.drop_table('news_items')
    op.drop_index('ix_model_name', table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index('ix_regime_session', table_name='market_regime_states')
    op.drop_table('market_regime_states')
    op.drop_index('ix_syslog_time', table_name='system_logs')
    op.drop_index('ix_syslog_category', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('strategies')
    op.drop_index('ix_sector_strength_session', table_name='sector_strength')
    op.drop_table('sector_strength')
    op.drop_index('ix_macro_pit', table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_index('ix_job_session_status', table_name='job_runs')
    op.drop_index('ix_job_recent', table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index('ix_indicator_session', table_name='indicator_values')
    op.drop_index('ix_indicator_lookup', table_name='indicator_values')
    op.drop_table('indicator_values')
    op.drop_index('ix_snapshot_digest', table_name='data_snapshots')
    op.drop_table('data_snapshots')
    op.drop_index('ix_quality_open', table_name='data_quality_issues')
    op.drop_index('ix_quality_blocking', table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index('ix_artifact_kind_name', table_name='artifact_versions')
    op.drop_table('artifact_versions')
    # ### end Alembic commands ###
