"""Phase 3 analytics

Revision ID: f86d4eb4d7ad
Revises: 0002_phase2_schema
Create Date: 2026-08-07 16:11:03.541764+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from tradeit.storage.tables import UTCDateTime

revision: str = "0003_phase3_analytics"
down_revision: str | None = "0002_phase2_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_definitions",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=96), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("calculation_version", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("timeframe", sa.String(length=8), nullable=False),
        sa.Column("output_type", sa.String(length=24), nullable=False),
        sa.Column("null_behaviour", sa.String(length=24), nullable=False),
        sa.Column(
            "input_datasets",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("warmup_periods", sa.Integer(), nullable=False),
        sa.Column("lookback_sessions", sa.Integer(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("availability", sa.Text(), nullable=True),
        sa.Column(
            "depends_on",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("deprecated", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("warmup_periods >= 0", name="ck_feature_warmup"),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index("ix_feature_kind", "feature_definitions", ["kind", "deprecated"], unique=False)
    op.create_index(
        "ix_feature_name",
        "feature_definitions",
        ["name", "version", "calculation_version"],
        unique=False,
    )
    op.create_table(
        "market_breadth_snapshots",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("universe_name", sa.String(length=64), nullable=False),
        sa.Column("universe_size", sa.Integer(), nullable=False),
        sa.Column("universe_digest", sa.String(length=64), nullable=False),
        sa.Column("evaluated", sa.Integer(), nullable=False),
        sa.Column("feature_set_digest", sa.String(length=64), nullable=False),
        sa.Column("advances", sa.Integer(), nullable=False),
        sa.Column("declines", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("advance_volume", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column("decline_volume", sa.Numeric(precision=28, scale=6), nullable=True),
        sa.Column(
            "pct_above_ma",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("new_highs", sa.Integer(), nullable=False),
        sa.Column("new_lows", sa.Integer(), nullable=False),
        sa.Column("ad_line", sa.BigInteger(), nullable=True),
        sa.Column("thrust_ratio", sa.Float(), nullable=True),
        sa.Column("low_confidence", sa.Boolean(), nullable=False),
        sa.Column(
            "notes",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "computed_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("evaluated <= universe_size", name="ck_breadth_evaluated"),
        sa.CheckConstraint("universe_size >= 0", name="ck_breadth_universe_size"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_date", "universe_name", "feature_set_digest", name="uq_breadth_snapshot"
        ),
    )
    op.create_index(
        "ix_breadth_session", "market_breadth_snapshots", ["session_date"], unique=False
    )
    op.create_table(
        "relative_strength_values",
        sa.Column("instrument_id", sa.BigInteger(), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("benchmark_symbol", sa.String(length=16), nullable=False),
        sa.Column("lookback", sa.Integer(), nullable=False),
        sa.Column("feature_set_digest", sa.String(length=64), nullable=False),
        sa.Column("security_return", sa.Float(), nullable=True),
        sa.Column("benchmark_return", sa.Float(), nullable=True),
        sa.Column("relative_performance", sa.Float(), nullable=True),
        sa.Column("excess_return", sa.Float(), nullable=True),
        sa.Column("relative_trend", sa.Float(), nullable=True),
        sa.Column("relative_momentum", sa.Float(), nullable=True),
        sa.Column("universe_percentile", sa.Float(), nullable=True),
        sa.Column("sector_percentile", sa.Float(), nullable=True),
        sa.Column("industry_percentile", sa.Float(), nullable=True),
        sa.Column("rs_score", sa.Float(), nullable=True),
        sa.Column("ranking_universe_size", sa.Integer(), nullable=True),
        sa.Column("ranking_universe_digest", sa.String(length=64), nullable=True),
        sa.Column(
            "computed_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lookback > 0", name="ck_rs_lookback"),
        sa.CheckConstraint(
            "rs_score IS NULL OR (rs_score >= 0 AND rs_score <= 100)", name="ck_rs_score_range"
        ),
        sa.CheckConstraint(
            "universe_percentile IS NULL OR (universe_percentile >= 0 AND universe_percentile <= 1)",
            name="ck_rs_percentile_range",
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id", "session_date", "benchmark_symbol", "lookback", "feature_set_digest"
        ),
        postgresql_partition_by="RANGE (session_date)",
    )
    op.create_index(
        "ix_rs_lookup",
        "relative_strength_values",
        ["instrument_id", "benchmark_symbol", "session_date"],
        unique=False,
    )
    op.create_index(
        "ix_rs_ranking",
        "relative_strength_values",
        ["session_date", "benchmark_symbol", "rs_score"],
        unique=False,
    )
    op.create_table(
        "volatility_regime_states",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("instrument_id", sa.BigInteger(), nullable=True),
        sa.Column("regime", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Integer(), nullable=False),
        sa.Column("realized_volatility", sa.Float(), nullable=True),
        sa.Column("volatility_percentile", sa.Float(), nullable=True),
        sa.Column("atr_percent", sa.Float(), nullable=True),
        sa.Column("gap_frequency", sa.Float(), nullable=True),
        sa.Column("cross_sectional_volatility", sa.Float(), nullable=True),
        sa.Column("expansion", sa.Float(), nullable=True),
        sa.Column(
            "supporting_evidence",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "contradicting_evidence",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("strategy_config_digest", sa.String(length=64), nullable=False),
        sa.Column(
            "computed_at",
            UTCDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100", name="ck_volatility_confidence"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_date",
            "scope",
            "instrument_id",
            "strategy_config_digest",
            name="uq_volatility_regime",
        ),
    )
    op.create_index(
        "ix_volatility_regime_session",
        "volatility_regime_states",
        ["session_date", "scope"],
        unique=False,
    )
    op.create_table(
        "feature_set_members",
        sa.Column("feature_set_digest", sa.String(length=64), nullable=False),
        sa.Column("feature_digest", sa.String(length=64), nullable=False),
        sa.Column("feature_name", sa.String(length=96), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_digest"], ["feature_definitions.digest"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("feature_set_digest", "feature_digest"),
    )
    op.create_index(
        "ix_feature_set_lookup",
        "feature_set_members",
        ["feature_set_digest", "feature_name"],
        unique=False,
    )
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # Same treatment as the Phase 2 partitioned tables: a partitioned table
        # with no partitions rejects every insert, and a DEFAULT partition is a
        # backstop that must stay empty.
        op.execute(
            "CREATE TABLE relative_strength_values_default "
            "PARTITION OF relative_strength_values DEFAULT"
        )
        op.execute(
            """
            DO $$
            DECLARE m date;
            BEGIN
                FOR m IN
                    SELECT generate_series(
                        date_trunc('month', CURRENT_DATE - interval '24 months'),
                        date_trunc('month', CURRENT_DATE + interval '2 months'),
                        interval '1 month'
                    )::date
                LOOP
                    PERFORM tradeit_ensure_month_partition(
                        'relative_strength_values'::regclass, m
                    );
                END LOOP;
            END $$;
            """
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "indicator_values_p202511",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202511_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202511_session_date_indicator_idx"),
        "indicator_values_p202511",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202511_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202511",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202606",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202606_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202606_session_date_indicator_idx"),
        "indicator_values_p202606",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202606_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202606",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202412",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202412_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202412_session_date_indicator_idx"),
        "indicator_values_p202412",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202412_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202412",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202501",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202501_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202501_session_date_indicator_idx"),
        "indicator_values_p202501",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202501_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202501",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_default",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_default_pkey")),
    )
    op.create_index(
        op.f("system_logs_default_logged_at_level_idx"),
        "system_logs_default",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_default_category_logged_at_idx"),
        "system_logs_default",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202504",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202504_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202504_logged_at_level_idx"),
        "system_logs_p202504",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202504_category_logged_at_idx"),
        "system_logs_p202504",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202505",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202505_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202505_logged_at_level_idx"),
        "system_logs_p202505",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202505_category_logged_at_idx"),
        "system_logs_p202505",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202509",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202509_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202509_logged_at_level_idx"),
        "system_logs_p202509",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202509_category_logged_at_idx"),
        "system_logs_p202509",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202504",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202504_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202504_session_date_indicator_idx"),
        "indicator_values_p202504",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202504_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202504",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202503",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202503_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202503_logged_at_level_idx"),
        "system_logs_p202503",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202503_category_logged_at_idx"),
        "system_logs_p202503",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202506",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202506_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202506_logged_at_level_idx"),
        "system_logs_p202506",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202506_category_logged_at_idx"),
        "system_logs_p202506",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202605",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202605_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202605_logged_at_level_idx"),
        "system_logs_p202605",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202605_category_logged_at_idx"),
        "system_logs_p202605",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202607",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202607_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202607_logged_at_level_idx"),
        "system_logs_p202607",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202607_category_logged_at_idx"),
        "system_logs_p202607",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202410",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202410_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202410_logged_at_level_idx"),
        "system_logs_p202410",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202410_category_logged_at_idx"),
        "system_logs_p202410",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202411",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202411_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202411_session_date_indicator_idx"),
        "indicator_values_p202411",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202411_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202411",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202512",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202512_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202512_logged_at_level_idx"),
        "system_logs_p202512",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202512_category_logged_at_idx"),
        "system_logs_p202512",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202609",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202609_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202609_logged_at_level_idx"),
        "system_logs_p202609",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202609_category_logged_at_idx"),
        "system_logs_p202609",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202409",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202409_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202409_logged_at_level_idx"),
        "system_logs_p202409",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202409_category_logged_at_idx"),
        "system_logs_p202409",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202602",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202602_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202602_logged_at_level_idx"),
        "system_logs_p202602",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202602_category_logged_at_idx"),
        "system_logs_p202602",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202505",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202505_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202505_session_date_indicator_idx"),
        "indicator_values_p202505",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202505_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202505",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202607",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202607_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202607_session_date_indicator_idx"),
        "indicator_values_p202607",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202607_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202607",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202509",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202509_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202509_session_date_indicator_idx"),
        "indicator_values_p202509",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202509_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202509",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202506",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202506_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202506_session_date_indicator_idx"),
        "indicator_values_p202506",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202506_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202506",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202502",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202502_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202502_session_date_indicator_idx"),
        "indicator_values_p202502",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202502_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202502",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202511",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202511_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202511_logged_at_level_idx"),
        "system_logs_p202511",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202511_category_logged_at_idx"),
        "system_logs_p202511",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202507",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202507_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202507_logged_at_level_idx"),
        "system_logs_p202507",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202507_category_logged_at_idx"),
        "system_logs_p202507",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202408",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202408_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202408_logged_at_level_idx"),
        "system_logs_p202408",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202408_category_logged_at_idx"),
        "system_logs_p202408",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202603",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202603_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202603_logged_at_level_idx"),
        "system_logs_p202603",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202603_category_logged_at_idx"),
        "system_logs_p202603",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202503",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202503_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202503_session_date_indicator_idx"),
        "indicator_values_p202503",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202503_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202503",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202610",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202610_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202610_session_date_indicator_idx"),
        "indicator_values_p202610",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202610_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202610",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202502",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202502_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202502_logged_at_level_idx"),
        "system_logs_p202502",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202502_category_logged_at_idx"),
        "system_logs_p202502",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202507",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202507_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202507_session_date_indicator_idx"),
        "indicator_values_p202507",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202507_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202507",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202608",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202608_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202608_session_date_indicator_idx"),
        "indicator_values_p202608",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202608_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202608",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202409",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202409_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202409_session_date_indicator_idx"),
        "indicator_values_p202409",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202409_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202409",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202508",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202508_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202508_logged_at_level_idx"),
        "system_logs_p202508",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202508_category_logged_at_idx"),
        "system_logs_p202508",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202510",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202510_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202510_session_date_indicator_idx"),
        "indicator_values_p202510",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202510_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202510",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202606",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202606_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202606_logged_at_level_idx"),
        "system_logs_p202606",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202606_category_logged_at_idx"),
        "system_logs_p202606",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202602",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202602_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202602_session_date_indicator_idx"),
        "indicator_values_p202602",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202602_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202602",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202604",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202604_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202604_session_date_indicator_idx"),
        "indicator_values_p202604",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202604_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202604",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202408",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202408_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202408_session_date_indicator_idx"),
        "indicator_values_p202408",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202408_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202408",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202603",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202603_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202603_session_date_indicator_idx"),
        "indicator_values_p202603",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202603_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202603",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202412",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202412_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202412_logged_at_level_idx"),
        "system_logs_p202412",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202412_category_logged_at_idx"),
        "system_logs_p202412",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202605",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202605_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202605_session_date_indicator_idx"),
        "indicator_values_p202605",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202605_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202605",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202501",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202501_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202501_logged_at_level_idx"),
        "system_logs_p202501",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202501_category_logged_at_idx"),
        "system_logs_p202501",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202601",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202601_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202601_session_date_indicator_idx"),
        "indicator_values_p202601",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202601_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202601",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202601",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202601_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202601_logged_at_level_idx"),
        "system_logs_p202601",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202601_category_logged_at_idx"),
        "system_logs_p202601",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202604",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202604_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202604_logged_at_level_idx"),
        "system_logs_p202604",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202604_category_logged_at_idx"),
        "system_logs_p202604",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202510",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202510_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202510_logged_at_level_idx"),
        "system_logs_p202510",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202510_category_logged_at_idx"),
        "system_logs_p202510",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202609",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202609_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202609_session_date_indicator_idx"),
        "indicator_values_p202609",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202609_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202609",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202508",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202508_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202508_session_date_indicator_idx"),
        "indicator_values_p202508",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202508_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202508",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202410",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202410_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202410_session_date_indicator_idx"),
        "indicator_values_p202410",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202410_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202410",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202610",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202610_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202610_logged_at_level_idx"),
        "system_logs_p202610",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202610_category_logged_at_idx"),
        "system_logs_p202610",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_p202512",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_p202512_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_p202512_session_date_indicator_idx"),
        "indicator_values_p202512",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_p202512_instrument_id_indicator_session_da_idx"),
        "indicator_values_p202512",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202608",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202608_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202608_logged_at_level_idx"),
        "system_logs_p202608",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202608_category_logged_at_idx"),
        "system_logs_p202608",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "system_logs_p202411",
        sa.Column(
            "logged_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False
        ),
        sa.Column("event_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("level", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.Column("category", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("event", sa.VARCHAR(length=96), autoincrement=False, nullable=False),
        sa.Column("message", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("portfolio_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("run_manifest_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        sa.Column("actor", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("logged_at", "event_id", name=op.f("system_logs_p202411_pkey")),
    )
    op.create_index(
        op.f("system_logs_p202411_logged_at_level_idx"),
        "system_logs_p202411",
        ["logged_at", "level"],
        unique=False,
    )
    op.create_index(
        op.f("system_logs_p202411_category_logged_at_idx"),
        "system_logs_p202411",
        ["category", "logged_at"],
        unique=False,
    )
    op.create_table(
        "indicator_values_default",
        sa.Column("instrument_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("session_date", sa.DATE(), autoincrement=False, nullable=False),
        sa.Column("indicator", sa.VARCHAR(length=48), autoincrement=False, nullable=False),
        sa.Column("timeframe", sa.VARCHAR(length=8), autoincrement=False, nullable=False),
        sa.Column("feature_set_digest", sa.VARCHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("value", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
        sa.Column("is_warm", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "computed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "instrument_id",
            "session_date",
            "indicator",
            "timeframe",
            "feature_set_digest",
            name=op.f("indicator_values_default_pkey"),
        ),
    )
    op.create_index(
        op.f("indicator_values_default_session_date_indicator_idx"),
        "indicator_values_default",
        ["session_date", "indicator"],
        unique=False,
    )
    op.create_index(
        op.f("indicator_values_default_instrument_id_indicator_session_da_idx"),
        "indicator_values_default",
        ["instrument_id", "indicator", "session_date"],
        unique=False,
    )
    op.drop_index("ix_feature_set_lookup", table_name="feature_set_members")
    op.drop_table("feature_set_members")
    op.drop_index("ix_volatility_regime_session", table_name="volatility_regime_states")
    op.drop_table("volatility_regime_states")
    op.drop_index("ix_rs_ranking", table_name="relative_strength_values")
    op.drop_index("ix_rs_lookup", table_name="relative_strength_values")
    op.drop_table("relative_strength_values")
    op.drop_index("ix_breadth_session", table_name="market_breadth_snapshots")
    op.drop_table("market_breadth_snapshots")
    op.drop_index("ix_feature_name", table_name="feature_definitions")
    op.drop_index("ix_feature_kind", table_name="feature_definitions")
    op.drop_table("feature_definitions")
    # ### end Alembic commands ###
