#!/usr/bin/env python
"""Generate the Phase 4 detector behaviour report.

Writes ``docs/PATTERN_VALIDATION.md`` from a live run rather than from numbers
transcribed by hand. Transcription is where reports go stale: a detector changes,
the prose does not, and the document quietly becomes fiction. Everything in the
generated file comes from this run and carries the baseline digest it was
produced under.

Usage::

    python scripts/phase4_report.py --trials 1000
    python scripts/phase4_report.py --trials 50 --quick   # smoke run

The default is deliberately large. The gate asks for enough samples to
characterise a distribution rather than to produce anecdotes, and a hundred
series tells you very little about a 99th percentile.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from tradeit.core.enums import Bartimeframe
from tradeit.patterns.competition import (
    coexistence_counts,
    run_matrix,
)
from tradeit.patterns.perturbation import (
    add_price_noise,
    add_volume_noise,
    perturb,
    shift_timing,
)
from tradeit.patterns.registry import (
    DETECTOR_ORDER,
    FAMILY_KIND,
    DetectorRegistry,
    phase4_baseline,
)
from tradeit.patterns.synthetic import BullFlagSpec, PatternGenerator, VcpSpec
from tradeit.patterns.validation import (
    CohortKind,
    characterise,
    cohorts_for,
)

GENERATOR = PatternGenerator()
REGISTRY = DetectorRegistry.from_config()

PERTURBATION_BASELINE = {
    "bull_flag": lambda s: GENERATOR.bull_flag(BullFlagSpec(breakout_sessions=3), seed=s),
    "vcp": lambda s: GENERATOR.vcp(VcpSpec(breakout_sessions=8), seed=s),
    "flat_base": lambda s: GENERATOR.flat_base(seed=s, breakout_sessions=8),
    "ascending_triangle": lambda s: GENERATOR.ascending_triangle(seed=s, touches=6),
    "pennant": lambda s: GENERATOR.pennant(seed=s, sessions=18),
    "cup_handle": lambda s: GENERATOR.cup_handle(seed=s, handle_sessions=22),
    "high_tight_flag": lambda s: GENERATOR.high_tight_flag(seed=s, pause_sessions=20),
    "double_bottom": lambda s: GENERATOR.double_bottom(seed=s, recovery_sessions=22),
    "inverse_head_shoulders": lambda s: GENERATOR.inverse_head_shoulders(
        seed=s, recovery_sessions=22
    ),
    "base_on_base": lambda s: GENERATOR.base_on_base(seed=s, second_sessions=28),
    "tight_consolidation": lambda s: GENERATOR.tight_consolidation(seed=s, sessions=20),
    "breakout_retest": lambda s: GENERATOR.breakout_retest(seed=s, hold_sessions=20),
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--trials", type=int, default=1000)
    parser.add_argument("--perturbation-trials", type=int, default=60)
    parser.add_argument("--out", type=Path, default=Path("docs/PATTERN_VALIDATION.md"))
    parser.add_argument("--quick", action="store_true", help="skip the slower sections")
    args = parser.parse_args()

    started = time.time()
    baseline = phase4_baseline()
    lines: list[str] = []

    lines.extend(_header(baseline, args.trials))
    lines.extend(_contracts())

    reports = []
    for name in DETECTOR_ORDER:
        detector = REGISTRY.detector(name, Bartimeframe.D1)
        cohorts = cohorts_for(name, GENERATOR)
        print(f"characterising {name} ({len(cohorts)} cohorts x {args.trials})", flush=True)
        report = characterise(detector, cohorts, trials=args.trials)
        reports.append(report)

    lines.extend(_distributions(reports))
    lines.extend(_frequency_separation(reports))
    lines.extend(_retest_investigation(reports))
    lines.extend(_cup_analysis())
    lines.extend(_competition())

    if not args.quick:
        print("running perturbation sweeps", flush=True)
        lines.extend(_stability(args.perturbation_trials))

    lines.extend(_weaknesses(reports))
    lines.append("")
    lines.append(f"*Generated in {time.time() - started:.0f}s.*")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out} ({len(lines)} lines)")
    return 0


def _header(baseline, trials: int) -> list[str]:
    return [
        "# Phase 4 — Detector Behaviour Report",
        "",
        "Generated by `scripts/phase4_report.py`. Every number here comes from the",
        "run that produced this file; nothing is transcribed by hand, because",
        "transcription is how a report quietly becomes fiction after the code moves on.",
        "",
        f"- **Generated**: {dt.datetime.now(dt.UTC).date().isoformat()}",
        f"- **Baseline**: `{baseline.label}`",
        f"- **Engine digest**: `{baseline.digest[:16]}`",
        f"- **Trials per cohort**: {trials}",
        "",
        "## How to read this",
        "",
        "**Nothing here is a trading threshold.** Phase 4 sets none. The distributions",
        "say where a quality floor *would* sit if someone wanted one; choosing it needs",
        "real data and out-of-sample evidence, and belongs to a later phase.",
        "",
        "**Nothing here was tuned against.** Adjusting a detector until a false-positive",
        "figure looked better would fit the detector to its own corpus, and the number",
        "would then describe the corpus rather than the detector.",
        "",
        "**Nothing here uses future returns.** No cohort is selected, weighted or scored",
        "by what price did afterwards. This report characterises pattern recognition;",
        "outcome research is a separate question and mixing the two would let a detector",
        "be validated by the thing it is supposed to be an input to.",
        "",
        "**Synthetic data does not establish real-world accuracy.** The generator draws",
        "what the detectors look for, so agreement on positives is close to tautological.",
        "What synthetic data *can* establish is internal consistency, ordering, stability",
        "and the shape of the response to noise — properties of the code rather than of",
        "markets. The real-data validation gate remains open.",
        "",
        "**Cohort kinds.** `positive` is the pattern as defined; `moderate` is real but",
        "unremarkable; `borderline` sits at the edge of the definition; `invalid` is a",
        "deliberately broken version of the same structure; `competing` is the nearest",
        "structural neighbour; `noise` is market-like randomness; `adversarial` is the",
        "trap specific to that family. Only `noise` and `adversarial` count as evidence",
        "against a detector — a broken pattern legitimately produces a low-scoring",
        "instance, and a competing structure may legitimately qualify under two",
        "definitions at once.",
        "",
    ]


def _contracts() -> list[str]:
    lines = [
        "## Detector registry",
        "",
        "| Detector | Kind | Version | Warm-up | Min coverage | Timeframes |",
        "| --- | --- | ---: | ---: | ---: | --- |",
    ]
    for entry in REGISTRY.all_entries():
        timeframes = ", ".join(str(t) for t in entry.timeframes)
        lines.append(
            f"| `{entry.name}` | {FAMILY_KIND[entry.name]} | v{entry.version} | "
            f"{entry.minimum_bars} | {entry.minimum_evidence_coverage:.0f}% | {timeframes} |"
        )
    lines.extend(
        [
            "",
            "Families absent from an intraday timeframe are absent because their",
            "definitions are stated in weeks. A high tight flag on 15-minute bars would",
            "be a 70% advance over eight hours: computable geometry, and a different",
            "claim wearing the name of a studied one.",
            "",
            "### Required components",
            "",
            "| Detector | Required | Optional |",
            "| --- | --- | --- |",
        ]
    )
    for entry in REGISTRY.all_entries():
        lines.append(
            f"| `{entry.name}` | {', '.join(f'`{c}`' for c in entry.required_components)} | "
            f"{', '.join(f'`{c}`' for c in entry.optional_components) or '—'} |"
        )
    lines.append("")
    return lines


def _distributions(reports) -> list[str]:
    lines = ["## Per-detector distributions", ""]
    for report in reports:
        lines.extend(
            [
                f"### `{report.detector}` (v{report.version})",
                "",
                "| Cohort | Kind | n | Cand | Mature | Term | Mean | Med | p75 | p90 "
                "| p95 | p99 | Max | ≥50 | ≥60 | ≥70 | ≥80 | ≥90 | Cov p50 |",
                "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: "
                "| ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
            ]
        )
        for cohort in report.cohorts:
            thresholds = cohort.threshold_rates()
            lines.append(
                f"| {cohort.cohort} | {cohort.kind} | {cohort.tested} "
                f"| {cohort.candidate_rate:.1%} | {cohort.mature_rate:.1%} "
                f"| {cohort.invalidation_rate:.1%} "
                f"| {cohort.mean:.1f} | {cohort.median:.1f} | {cohort.percentile(75):.1f} "
                f"| {cohort.percentile(90):.1f} | {cohort.percentile(95):.1f} "
                f"| {cohort.percentile(99):.1f} | {cohort.maximum:.1f} "
                f"| {thresholds['>=50']:.1%} | {thresholds['>=60']:.1%} "
                f"| {thresholds['>=70']:.1%} | {thresholds['>=80']:.1%} "
                f"| {thresholds['>=90']:.1%} | {cohort.coverage_percentile(50):.0f} |"
            )
        worst = report.worst_negative()
        lines.extend(
            [
                "",
                f"Worst negative cohort: **{worst.cohort if worst else 'none'}** "
                f"(p99 {worst.percentile(99):.1f}, ≥70 in {worst.high_quality_rate(70):.1%})."
                if worst
                else "",
                "",
            ]
        )
    return lines


def _frequency_separation(reports) -> list[str]:
    lines = [
        "## Candidate frequency is not high-quality frequency",
        "",
        "A detector may legitimately find many candidate structures and rate almost none",
        "of them highly. A detector that finds few and rates them all highly is a",
        "different animal with a different failure mode. Reported separately throughout;",
        "the columns below aggregate over the noise and adversarial cohorts only.",
        "",
        "| Detector | Candidate | Mature | ≥70 | ≥90 | Terminal |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for report in reports:
        negatives = [c for c in report.cohorts if c.kind.is_negative]
        if not negatives:
            continue
        tested = sum(c.tested for c in negatives)
        lines.append(
            f"| `{report.detector}` "
            f"| {sum(c.candidates for c in negatives) / tested:.1%} "
            f"| {sum(c.mature_rate * c.tested for c in negatives) / tested:.1%} "
            f"| {sum(c.high_quality_rate(70) * c.tested for c in negatives) / tested:.1%} "
            f"| {sum(c.high_quality_rate(90) * c.tested for c in negatives) / tested:.1%} "
            f"| {sum(c.invalidation_rate * c.tested for c in negatives) / tested:.1%} |"
        )
    lines.append("")
    return lines


def _retest_investigation(reports) -> list[str]:
    report = next((r for r in reports if r.detector == "breakout_retest"), None)
    if report is None:
        return []
    lines = [
        "## Breakout retest: decomposing the noise rate",
        "",
        "The family's random-walk candidate rate is the single most-discussed number in",
        "this phase, and the gate is right that a headline percentage is the wrong thing",
        "to act on. Decomposed:",
        "",
        "| Noise cohort | Candidate | Mature | ≥60 | ≥70 | ≥80 | ≥90 | Terminal |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for cohort in report.cohorts:
        if not cohort.kind.is_negative:
            continue
        rates = cohort.threshold_rates()
        lines.append(
            f"| {cohort.cohort} | {cohort.candidate_rate:.1%} | {cohort.mature_rate:.1%} "
            f"| {rates['>=60']:.1%} | {rates['>=70']:.1%} | {rates['>=80']:.1%} "
            f"| {rates['>=90']:.1%} | {cohort.invalidation_rate:.1%} |"
        )
    positive = next((c for c in report.cohorts if c.kind is CohortKind.POSITIVE), None)
    if positive:
        lines.extend(
            [
                "",
                f"For comparison, the drawn structure: candidate {positive.candidate_rate:.1%}, "
                f"≥70 in {positive.high_quality_rate(70):.1%}, ≥90 in "
                f"{positive.high_quality_rate(90):.1%}.",
            ]
        )
    lines.extend(
        [
            "",
            "**The finding.** Candidate frequency is high and it is not an artefact. Every",
            "ingredient of the definition — a level, a close above it, a return to it — is a",
            "*single event*, and noise supplies single events readily. A cup or a high tight",
            "flag requires a sustained shape over dozens of sessions, which noise does not.",
            "",
            "**What was done about it, and what was not.** Four structural requirements were",
            "added during construction because they are definitionally right: three touches",
            "spanning at least twenty sessions, price below the level for 85% of them, a",
            "break of at least one ATR, and that break sustained over three closes. Each cut",
            "the rate. None was chosen to hit a number, and no threshold has been moved since",
            "the rate was measured. Lowering it further by tuning would produce a detector",
            "fitted to this corpus.",
            "",
            "**The consequence for later phases**, stated concretely: a retest reading is weak",
            "evidence on its own. It should be weighted well below a cup or a VCP reading of",
            "comparable score, and real labelled data is what will say by how much.",
            "",
        ]
    )
    return lines


def _cup_analysis() -> list[str]:
    from tradeit.patterns.detectors import CupHandleDetector

    detector = CupHandleDetector()
    rows = []
    for label, series in (
        ("cup (textbook)", GENERATOR.cup_handle()),
        ("v-bottom", GENERATOR.v_bottom()),
        ("incomplete recovery", GENERATOR.incomplete_recovery()),
        ("deep handle", GENERATOR.cup_handle(handle_depth_ratio=0.70)),
    ):
        found = detector.detect(series.bars, series.last_session)
        if not found:
            rows.append((label, 0.0, {}))
            continue
        best = found[0]
        rows.append(
            (label, best.quality, {c.name: c.score for c in best.components if not c.unavailable})
        )

    names = sorted({n for _, _, comps in rows for n in comps})
    lines = [
        "## Cup and Handle versus the V-bottom",
        "",
        "The gate asks for this to be analysed rather than cosmetically tuned. Component",
        "by component:",
        "",
        "| Component | " + " | ".join(label for label, _, _ in rows) + " |",
        "| --- | " + " | ".join("---:" for _ in rows) + " |",
    ]
    for name in names:
        cells = " | ".join(f"{comps.get(name, 0.0):.1f}" if comps else "—" for _, _, comps in rows)
        lines.append(f"| `{name}` | {cells} |")
    lines.append("| **composite** | " + " | ".join(f"**{q:.1f}**" for _, q, _ in rows) + " |")
    lines.extend(
        [
            "",
            "**What differentiates them.** Exactly one dimension: `bottom_roundness`. The",
            "V-bottom is generated with the same rims, the same depth, the same duration and",
            "the same handle, so every other component is measuring an identical structure",
            "and returns an identical number. That is the generator working as intended —",
            "the cohort exists to isolate roundness — and it is also why the composite gap is",
            "what it is.",
            "",
            "**Does the scoring reflect the stated definition?** Yes. The module documents",
            'roundness as "the part that matters most and is easiest to fake", and measures',
            "it as time spent near the low rather than by fitting a curve, because fitting a",
            "curve rewards charts that look like a picture of a cup while this rewards charts",
            "where supply was actually absorbed. The component separates the two structures",
            "decisively.",
            "",
            "**The limitation, stated plainly.** Pattern quality is multidimensional, and a",
            "structure excellent in every dimension except one still receives a high",
            "composite. The composite gap is roughly what one component's weight is worth,",
            "and that is arithmetic rather than a defect. Raising `bottom_roundness`'s weight",
            "until the V-bottom fell below some line would be tuning a weight to move a",
            "number, which the brief forbids and which would also degrade the score of every",
            "genuine cup whose bottom is merely good rather than perfect.",
            "",
            "**What would justify recalibration.** Human labels and empirical outcomes on real",
            "cups and real V-bottoms. If labellers consistently reject V-bottoms that this",
            "detector scores in the eighties, the weight is wrong and there will be evidence",
            "for what it should be. Until then, changing it would be substituting a preference",
            "for a measurement.",
            "",
            "The same arithmetic explains the `deep handle` column: a handle retracing 70% of",
            "the cup is scored down decisively on `handle_structure` and the composite falls",
            "by that component's weight. Reading the composite alone would understate how",
            "clearly the detector identified the flaw; the component breakdown is the point.",
            "",
        ]
    )
    return lines


def _competition() -> list[str]:
    cases = run_matrix(REGISTRY, GENERATOR)
    lines = [
        "## Competing-pattern matrix",
        "",
        "Exclusivity is not forced. A window that is a tight consolidation at 78 and a",
        "bull flag at 74 is one piece of chart with two names, and choosing between them",
        "early discards what a later scoring stage is better placed to use. What follows",
        "records which families coexist, and — the part that matters — which component",
        "readings separate them.",
        "",
    ]
    for case in cases:
        lines.extend(["```", case.format_block(), "```", ""])

    lines.extend(
        [
            "### How often each pair coexists",
            "",
            "| Family A | Family B | Cases |",
            "| --- | --- | ---: |",
        ]
    )
    for (first, second), count in list(coexistence_counts(cases).items())[:20]:
        lines.append(f"| `{first}` | `{second}` | {count} |")
    lines.extend(
        [
            "",
            "**Confusion cases worth knowing.** In several rows a family that was not drawn",
            "outscores the one that was. That is recorded rather than corrected: the flat",
            "base scoring above the ascending triangle on a triangle series is the honest",
            "report that a triangle with rising lows under a ceiling *is* a shallow base with",
            "a flat top, and the two definitions genuinely overlap there. The component rows",
            "are what distinguish them, and the margin column is what a later stage most",
            "needs, because a small margin says the family label is the least reliable part",
            "of the reading.",
            "",
        ]
    )
    return lines


def _stability(trials: int) -> list[str]:
    lines = [
        "## Score stability under perturbation",
        "",
        "Smooth is not the goal; the right kind of discontinuity is. A jump accompanied",
        "by a moved structural start, a state change, or a pattern appearing is a genuine",
        "structural transition. The same jump with none of those is a threshold being",
        "crossed where reality is continuous, and only the second is a finding. The",
        "`unexplained` column counts the second kind.",
        "",
        "| Detector | Dimension | n | Median Δ | p95 Δ | Max Δ | Cause of max | Unexplained |",
        "| --- | --- | ---: | ---: | ---: | ---: | --- | ---: |",
    ]
    dimensions = (
        (
            "price_noise_0.1pct",
            "every bar scaled by ~0.1%",
            lambda series, seed: add_price_noise(series, 0.001, seed=seed + 7000),
        ),
        (
            "price_noise_0.3pct",
            "every bar scaled by ~0.3%",
            lambda series, seed: add_price_noise(series, 0.003, seed=seed + 8000),
        ),
        (
            "price_noise_1pct",
            "every bar scaled by ~1%; large enough to move pivots",
            lambda series, seed: add_price_noise(series, 0.010, seed=seed + 8500),
        ),
        (
            "volume_noise_15pct",
            "volume jittered, prices untouched",
            lambda series, seed: add_volume_noise(series, 0.15, seed=seed + 9000),
        ),
        (
            "timing_shift_3",
            "three leading bars dropped",
            lambda series, _seed: shift_timing(series, 3),
        ),
    )
    for name in DETECTOR_ORDER:
        detector = REGISTRY.detector(name, Bartimeframe.D1)
        for dimension, intent, mutate in dimensions:
            report = perturb(
                detector,
                PERTURBATION_BASELINE[name],
                mutate,
                dimension=dimension,
                intent=intent,
                trials=trials,
            )
            summary = report.summary()
            lines.append(
                f"| `{name}` | {dimension} | {summary['tested']} "
                f"| {summary['median_delta']} | {summary['p95_delta']} "
                f"| {summary['max_delta']} | {summary['max_delta_cause']} "
                f"| {summary['unexplained_jumps']} |"
            )
    lines.append("")
    return lines


def _weaknesses(reports) -> list[str]:
    lines = [
        "## Known weaknesses, by detector",
        "",
        "Derived from the worst-scoring negative cohort for each family. These are where",
        "real-data validation should look first.",
        "",
        "| Detector | Weakest against | p99 | ≥70 | Why it happens |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for report in reports:
        worst = report.worst_negative()
        if worst is None:
            lines.append(f"| `{report.detector}` | — | — | — | no negative cohort scored |")
            continue
        lines.append(
            f"| `{report.detector}` | {worst.cohort} | {worst.percentile(99):.1f} "
            f"| {worst.high_quality_rate(70):.1%} | {worst.intent} |"
        )
    lines.extend(
        [
            "",
            "## What remains open",
            "",
            "**Real-market validation.** No claim in this document is evidence about",
            "real-world precision, recall or profitability. The corpus is synthetic, the",
            "generator draws what the detectors look for, and market-data egress is blocked",
            "in this environment. `docs/PATTERN_LABELING.md` specifies the protocol to run",
            "when data is available, including the sampling rules that keep future returns",
            "out of the structural labelling decision.",
            "",
            "**Cross-family calibration.** A quality of 80 from one detector is not a quality",
            "of 80 from another. Each score is relative to its own structural definition and",
            "no mapping between them exists, because establishing one needs labelled data",
            "this phase does not have. Nothing downstream should compare raw scores across",
            "families until it does.",
            "",
        ]
    )
    return lines


if __name__ == "__main__":
    raise SystemExit(main())
