#!/usr/bin/env python
"""Generate the Phase 5 breakout behaviour report.

Writes ``docs/BREAKOUT_VALIDATION.md`` from a live run rather than from numbers
transcribed by hand. Transcription is where reports go stale: the engine
changes, the prose does not, and the document quietly becomes fiction.
Everything in the generated file comes from this run and carries the
configuration digest it was produced under.

Usage::

    python scripts/phase5_report.py --trials 200
    python scripts/phase5_report.py --trials 20 --quick   # smoke run

**Nothing here is a trading success rate.** Every rate below describes the
engine's behaviour on a synthetic corpus. "72% of clean synthetic breakouts
reached CONFIRMED" says nothing whatever about how often real breakouts work,
and any sentence in the output that could be read that way is a bug in this
script.
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from tradeit.breakouts.config import BreakoutEngineConfig
from tradeit.breakouts.engine import BreakoutEngine
from tradeit.breakouts.perturbation import PerturbationKind, sweep
from tradeit.breakouts.scoring import BREAKOUT_SCORER_VERSION
from tradeit.breakouts.synthetic import (
    ADVERSARIAL_SCENARIOS,
    CONTROLLED_SCENARIOS,
    BreakoutGenerator,
    all_scenarios,
)
from tradeit.breakouts.validation import (
    QUALITY_THRESHOLDS,
    characterise,
    profile_comparison,
    separation,
)

GENERATOR = BreakoutGenerator()

#: Scenarios the stability sweep runs over. Four shapes rather than all thirty:
#: a stability figure is a property of the engine, and thirty rows of the same
#: finding is noise rather than evidence.
STABILITY_SCENARIOS = (
    "clean_breakout",
    "weak_breakout",
    "gap_breakout",
    "successful_retest",
)

STABILITY_MAGNITUDES: dict[PerturbationKind, list[float]] = {
    PerturbationKind.PRICE_NOISE: [0.0005, 0.001, 0.002],
    PerturbationKind.VOLUME_NOISE: [0.02, 0.05, 0.10],
    PerturbationKind.TIMING: [1, 2, 3],
    PerturbationKind.LEVEL_SHIFT: [-0.002, -0.001, 0.001, 0.002],
    PerturbationKind.ATR_SHIFT: [-2, -1, 1, 2],
    PerturbationKind.GAP_SIZE: [0.005, 0.01],
    PerturbationKind.CLOSE_LOCATION: [-0.1, 0.05],
    PerturbationKind.RETEST_DEPTH: [0.002, 0.005],
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--trials", type=int, default=200)
    parser.add_argument("--stability-trials", type=int, default=5)
    parser.add_argument("--profile-trials", type=int, default=40)
    parser.add_argument("--quick", action="store_true", help="skip the profile table")
    parser.add_argument("--out", type=Path, default=Path("docs/BREAKOUT_VALIDATION.md"))
    args = parser.parse_args()

    config = BreakoutEngineConfig()
    started = time.perf_counter()

    results = []
    for scenario in all_scenarios(GENERATOR):
        print(f"characterising {scenario.name} ({args.trials} trials)", file=sys.stderr)
        results.append(characterise(scenario, trials=args.trials, config=config))

    lines: list[str] = []
    lines += _header(config, args.trials)
    lines += _corpus()
    lines += _distributions(results)
    lines += _thresholds(results)
    lines += _states(results)
    lines += _paths(results)
    if not args.quick:
        print("comparing profiles", file=sys.stderr)
        lines += _profiles(config, args.profile_trials)
    print("running perturbation sweeps", file=sys.stderr)
    lines += _stability(config, args.stability_trials)
    lines += _weaknesses(results)
    lines += _limits()

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    elapsed = time.perf_counter() - started
    print(f"wrote {args.out} ({len(lines)} lines) in {elapsed:.1f}s", file=sys.stderr)
    return 0


# ---------------------------------------------------------------------------


def _header(config: BreakoutEngineConfig, trials: int) -> list[str]:
    engine = BreakoutEngine(config)
    return [
        "# Breakout engine behaviour",
        "",
        "**Generated by `scripts/phase5_report.py`. Do not edit by hand.**",
        "",
        f"- Generated: {dt.datetime.now(tz=dt.UTC).date().isoformat()}",
        f"- Trials per scenario: {trials}",
        f"- Scorer version: {BREAKOUT_SCORER_VERSION}",
        f"- Config digest: `{engine.config_digest()}`",
        f"- Active profile: `{config.active_profile}`",
        "",
        "## What these numbers are, and are not",
        "",
        "Every figure below describes **the engine's behaviour on a synthetic",
        "corpus**. None of them is a trading success rate. A confirmation rate is",
        "the fraction of synthetic series on which the configured evidence policy",
        "was satisfied; it is not a claim that confirmed breakouts work, and no",
        "sentence in this document should be read as one.",
        "",
        "Real-market validation is **explicitly open**. Nothing here has been",
        "measured against a price series the engine did not generate, and no",
        "threshold in the configuration has been fitted to any outcome — Phase 5",
        "is forbidden from doing so, and Phase 9 is the phase with a walk-forward",
        "harness to do it properly.",
        "",
    ]


def _corpus() -> list[str]:
    lines = [
        "## The corpus",
        "",
        f"{len(CONTROLLED_SCENARIOS)} controlled scenarios and",
        f"{len(ADVERSARIAL_SCENARIOS)} adversarial ones. Every scenario is a",
        "parameterisation of one builder, so a difference in output is",
        "attributable to the field that was changed and to nothing else.",
        "",
        "| Scenario | Kind | Intent |",
        "| --- | --- | --- |",
    ]
    for scenario in all_scenarios(GENERATOR):
        kind = "adversarial" if scenario.adversarial else "controlled"
        lines.append(f"| `{scenario.name}` | {kind} | {scenario.intent} |")
    lines.append("")
    return lines


def _distributions(results) -> list[str]:
    lines = [
        "## Outcome distributions",
        "",
        "Six rates rather than one accuracy. Breakout, confirmed, rejected,",
        "failed and expired are different outcomes with different meanings, and a",
        'single "success rate" would have to pick which of them counts as',
        "success — a decision Phase 5 is not entitled to make.",
        "",
        "`attempts` is the mean number of breakout events the series produced. A",
        "base that oscillates up to its level routinely turns one attempt back",
        "before the real break, and each attempt is a separate record.",
        "",
        "| Scenario | Adv | Attempts | Breakout | Confirmed | Rejected "
        "| Failed | Expired | Retest |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for stats in results:
        lines.append(
            f"| `{stats.scenario}` | {'Y' if stats.adversarial else ''} "
            f"| {stats.mean_attempts:.1f} "
            f"| {stats.breakout_rate:.0%} | {stats.confirmed_rate:.0%} "
            f"| {stats.rejected_rate:.0%} | {stats.failed_rate:.0%} "
            f"| {stats.expired_rate:.0%} | {stats.retest_rate:.0%} |"
        )
    lines.append("")

    lines += [
        "### Score medians",
        "",
        "Four numbers per scenario, deliberately not three and definitely not one.",
        "Quality is frozen at the breakout bar; confirmation accumulates after it;",
        "coverage says how much of the intended evidence was available; confidence",
        "says how certain the engine is that it identified the event correctly.",
        "",
        "| Scenario | Quality | Confirmation | Coverage | Confidence |",
        "| --- | --- | --- | --- | --- |",
    ]
    for stats in results:
        lines.append(
            f"| `{stats.scenario}` | {stats.median_quality:.1f} "
            f"| {stats.median_confirmation:.1f} | {stats.median_coverage:.1f} "
            f"| {stats.median_confidence:.1f} |"
        )
    lines.append("")
    lines.append(
        f"Separation at quality 70 (mean controlled rate minus mean adversarial "
        f"rate): **{separation(results, 70.0):.3f}**. A blunt single number, "
        "published alongside the distributions rather than instead of them. No "
        "cost is attached to either error, because attaching one is a later "
        "phase's decision."
    )
    lines.append("")
    return lines


def _thresholds(results) -> list[str]:
    header = " | ".join(f"≥{int(t)}" for t in QUALITY_THRESHOLDS)
    lines = [
        "## Breakout quality above thresholds",
        "",
        "Cumulative, and computed with the zeros included: a series that never",
        "broke out counts as zero rather than being excluded. Excluding them",
        "would describe the subset that happened to fire, which is a different",
        "and flattering question.",
        "",
        f"| Scenario | Adv | {header} |",
        "| --- | --- | " + " | ".join("---" for _ in QUALITY_THRESHOLDS) + " |",
    ]
    for stats in results:
        rates = " | ".join(f"{stats.high_quality_rate(t):.0%}" for t in QUALITY_THRESHOLDS)
        lines.append(f"| `{stats.scenario}` | {'Y' if stats.adversarial else ''} | {rates} |")
    lines.append("")
    return lines


def _states(results) -> list[str]:
    lines = [
        "## Final states",
        "",
        "The state each replay ended in. Not all are terminal: a series can run",
        "out of bars while an event is still approaching or pending, and those",
        "rows are shown as they are rather than being forced into an outcome.",
        "",
        "Expiry and failure are separated throughout. Expiry means nothing",
        "happened in time; failure means something happened and it went the wrong",
        "way. Merging them would inflate every failure rate with non-events.",
        "",
        "| Scenario | Final states |",
        "| --- | --- |",
    ]
    for stats in results:
        counts = ", ".join(f"{k} {v}" for k, v in stats.state_counts().items())
        lines.append(f"| `{stats.scenario}` | {counts} |")
    lines.append("")
    return lines


def _paths(results) -> list[str]:
    lines = [
        "## How confirmations arrive",
        "",
        "Three paths exist because there are genuinely three ways a breakout",
        "earns belief. Which one produced a confirmation is recorded on the",
        "event, so this table is data rather than an assumption.",
        "",
        "| Scenario | Paths taken |",
        "| --- | --- |",
    ]
    for stats in results:
        counts = stats.path_counts()
        if not counts:
            continue
        lines.append(
            f"| `{stats.scenario}` | " + ", ".join(f"{k} {v}" for k, v in counts.items()) + " |"
        )
    lines.append("")
    return lines


def _profiles(config: BreakoutEngineConfig, trials: int) -> list[str]:
    table = profile_comparison(trials=trials, config=config)
    lines = [
        "## What the profiles buy",
        "",
        "The names describe evidence requirements, not risk appetite. AGGRESSIVE",
        "does not mean a bigger position — it means a first strong close is",
        "accepted. If CONSERVATIVE did not confirm materially less on the",
        "adversarial corpus, the profiles would not be doing the work their names",
        "claim, which is why this table exists rather than the assertion alone.",
        "",
        "| Profile | Controlled confirmed | Adversarial confirmed | Controlled failed |",
        "| --- | --- | --- | --- |",
    ]
    for name in ("conservative", "balanced", "aggressive"):
        row = table.get(name)
        if row is None:
            continue
        lines.append(
            f"| `{name}` | {row['controlled_confirmed_rate']:.0%} "
            f"| {row['adversarial_confirmed_rate']:.0%} "
            f"| {row['controlled_failed_rate']:.0%} |"
        )
    lines.append("")
    return lines


def _stability(config: BreakoutEngineConfig, trials: int) -> list[str]:
    lines = [
        "## Stability under perturbation",
        "",
        "The property is not that the score never moves. It is that a small,",
        "structurally irrelevant change produces a small change, and that a large",
        "change is explained by something structural having actually changed —",
        "the event ending somewhere else, or a different bar becoming the",
        "breakout.",
        "",
        "`proportional` says whether the median response grows with the",
        "perturbation. A response that grows is a slope; one that is flat and",
        "then leaps is a cliff, and only the second is a stability problem.",
        "",
        "| Scenario | Perturbation | n | Median | p90 | Max | Cause of max "
        "| Proportional | Unexplained |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    total_unexplained = 0
    for name in STABILITY_SCENARIOS:
        series = getattr(GENERATOR, name)(seed=0)
        for kind, magnitudes in STABILITY_MAGNITUDES.items():
            report = sweep(
                series,
                kind,
                magnitudes,
                trials=trials,
                config=config,
                builder=GENERATOR.build,
            )
            data = report.summary()
            total_unexplained += int(data["unexplained_jumps"])
            lines.append(
                f"| `{name}` | {data['kind']} | {data['tested']} "
                f"| {data['median_delta']:.2f} | {data['p90_delta']:.2f} "
                f"| {data['max_delta']:.2f} | {data['max_cause']} "
                f"| {'yes' if data['proportional'] else 'no'} "
                f"| {data['unexplained_jumps']} |"
            )
    lines.append("")
    lines.append(
        f"**Unexplained large jumps across every row: {total_unexplained}.** A "
        "large jump is a move of more than 10 quality points with neither the "
        "terminal state nor the breakout bar having changed."
    )
    lines.append("")
    return lines


def _weaknesses(results) -> list[str]:
    by_name = {stats.scenario: stats for stats in results}
    adversarial = sorted(
        (s for s in results if s.adversarial),
        key=lambda s: s.confirmed_rate,
        reverse=True,
    )
    lines = [
        "## Known weaknesses",
        "",
        "Reported rather than tuned away. Phase 5 is explicitly forbidden from",
        "moving a threshold because an adversarial distribution looks",
        "unfavourable, and the honest response to a high adversarial rate is to",
        "publish it and say what causes it.",
        "",
        "### Adversarial scenarios by confirmation rate",
        "",
        "| Scenario | Confirmed | Median quality | Median confidence |",
        "| --- | --- | --- | --- |",
    ]
    for stats in adversarial[:6]:
        lines.append(
            f"| `{stats.scenario}` | {stats.confirmed_rate:.0%} "
            f"| {stats.median_quality:.1f} | {stats.median_confidence:.1f} |"
        )
    lines.append("")

    drift = by_name.get("low_volume_drift")
    trend = by_name.get("no_prior_resistance")
    if drift is not None and trend is not None:
        lines += [
            "### The engine cannot tell a level from a line",
            "",
            f"`low_volume_drift` confirms at {drift.confirmed_rate:.0%} and",
            f"`no_prior_resistance` at {trend.confirmed_rate:.0%}. Both are",
            "adversarial by construction: in one, price drifts above an arbitrary",
            "level on collapsing volume; in the other, an uninterrupted trend",
            "crosses a level that was never tested.",
            "",
            "This is a real limitation and it is worth being precise about where",
            "it lives. **The engine is not given the boundary's validity to",
            "judge** — deciding whether a level is a structure is Phase 4's job,",
            "and deciding whether a structure is still live is the monitor's",
            "filter. Handed a level, the engine faithfully reports that price",
            "closed above it.",
            "",
            "Two things do discriminate, and both are visible in the table above:",
            f"the median *quality* on these scenarios is {drift.median_quality:.0f}",
            f"and {trend.median_quality:.0f} against",
            f"{by_name['clean_breakout'].median_quality:.0f} for a clean breakout,",
            "and an unattached or single-touch boundary drops the *confidence*",
            "score sharply. A consumer reading state alone will be misled; one",
            "reading the four numbers will not.",
            "",
        ]

    weak = by_name.get("poor_confidence_boundary")
    clean = by_name.get("clean_breakout")
    if weak is not None and clean is not None:
        lines += [
            "### Quality and confidence are genuinely different numbers",
            "",
            "`poor_confidence_boundary` is the clean series against a level",
            "defined by a single bar. Median quality",
            f"{weak.median_quality:.0f} against {clean.median_quality:.0f} —",
            "similar, because the price action *is* similar — while median",
            f"confidence falls from {clean.median_confidence:.0f} to",
            f"{weak.median_confidence:.0f}. That gap is the whole point of",
            "keeping the two apart.",
            "",
        ]
    return lines


def _limits() -> list[str]:
    return [
        "## Limits of this report",
        "",
        "1. **Synthetic only.** ADR-0018's limits apply unchanged. These series",
        "   were generated by the same repository that evaluates them, and the",
        "   generator's idea of a breakout is not the market's.",
        "2. **No profitability measurement anywhere.** No win rate, no forward",
        "   return, no expectancy. Item 23 of the Phase 4 gate and the Phase 5",
        "   brief both forbid it, and there is no return series in this process",
        "   to compute one from.",
        "3. **No fitted thresholds.** Every default was chosen structurally and",
        "   documented with its reasoning. Phase 9 may argue with them from",
        "   out-of-sample evidence; this report is not that argument.",
        "4. **Rates are conditional on the corpus.** A confirmation rate here is",
        "   a fact about thirty scenarios, not about a universe.",
        "5. **The adversarial corpus is not exhaustive.** It contains the failure",
        "   modes that were thought of. Real data will contain others.",
        "",
    ]


if __name__ == "__main__":
    raise SystemExit(main())
