"""Interfaces for order construction, cost modelling, and fills.

The layer that turns an approved allocation into orders, and orders into fills.
The design constraint that shapes it: **paper trading and live trading use the
same code path**, differing only in which :class:`~tradeit.data.provider.BrokerProvider`
is injected. A paper mode that takes a shortcut anywhere is a paper mode whose
results say nothing about live behaviour.

The cost model is separated from the venue because it is the part most likely to
be wrong and most consequential when it is. A strategy that trades often can be
profitable at 2 basis points of slippage and unprofitable at 15, and the
difference between those two numbers is entirely a modelling assumption. Making
it a swappable, explicitly-parameterised component means the assumption can be
stress-tested instead of buried.
"""

from __future__ import annotations

import datetime as dt
from dataclasses import dataclass
from decimal import Decimal
from typing import Protocol, runtime_checkable

from tradeit.core.enums import OrderSide, OrderType, TimeInForce
from tradeit.core.models import OhlcvBar


@dataclass(frozen=True, slots=True)
class OrderRequest:
    """An order the platform intends to place.

    ``client_order_id`` is generated by us before submission, not assigned by
    the broker afterwards. That ordering is what makes a retry safe: if a
    submission times out, resubmitting the same id is a no-op at the broker
    rather than a second position. Without it, "did that order go through?"
    after a network failure has no safe answer.

    ``intent`` carries why the order exists (which signal, which exit rule) so
    the trade journal can be assembled without inference.
    """

    client_order_id: str
    portfolio_id: int
    instrument_id: int
    side: OrderSide
    order_type: OrderType
    quantity: Decimal
    limit_price: Decimal | None = None
    stop_price: Decimal | None = None
    time_in_force: TimeInForce = TimeInForce.DAY
    intent: str = ""
    parent_position_id: int | None = None

    def __post_init__(self) -> None:
        if self.quantity <= 0:
            raise ValueError("order quantity must be positive")
        if self.order_type in (OrderType.LIMIT, OrderType.STOP_LIMIT) and self.limit_price is None:
            raise ValueError(f"{self.order_type} requires a limit_price")
        if self.order_type in (OrderType.STOP, OrderType.STOP_LIMIT) and self.stop_price is None:
            raise ValueError(f"{self.order_type} requires a stop_price")

    @property
    def is_entry(self) -> bool:
        return self.side in (OrderSide.BUY, OrderSide.SELL_SHORT)


@dataclass(frozen=True, slots=True)
class Fill:
    """An execution against an order.

    Partial fills are separate rows rather than a mutated quantity, because the
    average price of a position built across three fills at three prices is only
    reconstructible if all three were kept.

    ``commission`` and ``slippage`` are recorded separately from ``price``:
    commission is a fact, slippage is the difference between the price we
    expected and the price we got, and conflating them makes it impossible to
    tell a costly strategy from a badly-modelled one.
    """

    order_id: int
    instrument_id: int
    side: OrderSide
    quantity: Decimal
    price: Decimal
    filled_at: dt.datetime
    commission: Decimal = Decimal(0)
    slippage: Decimal = Decimal(0)
    venue: str = ""

    @property
    def gross_value(self) -> Decimal:
        return self.price * self.quantity

    @property
    def net_value(self) -> Decimal:
        """Cash effect including commission, signed by direction."""
        if self.side in (OrderSide.BUY, OrderSide.BUY_TO_COVER):
            return -(self.gross_value + self.commission)
        return self.gross_value - self.commission


@dataclass(frozen=True, slots=True)
class CostEstimate:
    """Modelled cost of executing an order, before it is placed."""

    commission: Decimal
    spread_cost: Decimal
    market_impact: Decimal
    expected_fill_price: Decimal
    participation_rate: float

    @property
    def total(self) -> Decimal:
        return self.commission + self.spread_cost + self.market_impact


@runtime_checkable
class CostModel(Protocol):
    """Estimates execution cost. The most consequential modelling assumption here.

    Implementations must make cost **increase with participation rate**. A model
    with fixed basis-point slippage lets a backtest buy a million shares of an
    illiquid name at the closing price, which is where a large share of
    fictitious backtest returns come from.
    """

    @property
    def name(self) -> str:
        """A stable identifier for this implementation.

        A read-only property rather than ``name: str``. The attribute form
        demands a *settable* member, which no frozen dataclass can offer --
        and every implementation of this protocol is one, because these
        components are stateless and configured once. A mutable attribute
        still satisfies this, so the change only ever admits more.
        """
        ...

    @property
    def parameters(self) -> dict[str, object]: ...

    def estimate(
        self,
        order: OrderRequest,
        reference_bar: OhlcvBar,
        average_dollar_volume: Decimal | None = None,
    ) -> CostEstimate: ...


@runtime_checkable
class FillModel(Protocol):
    """Decides whether and at what price a simulated order fills.

    Used by the backtester and the paper broker. The rules it must respect are
    the ones naive simulators break:

    * **No fill outside the bar's range.** A limit at 100 does not fill on a day
      whose low was 100.50, however much the strategy would have liked it to.
    * **Gaps are respected.** A stop at 50 on a day that opens at 44 fills at
      44, not 50. Backtests that assume stops fill at their trigger price
      systematically understate drawdown.
    * **Volume caps participation.** An order for 30% of a session's volume does
      not fill in full at one price.
    """

    @property
    def name(self) -> str: ...

    @property
    def parameters(self) -> dict[str, object]: ...

    def simulate(
        self,
        order: OrderRequest,
        bar: OhlcvBar,
        cost: CostEstimate,
    ) -> Fill | None: ...


@runtime_checkable
class ExecutionService(Protocol):
    """Places orders through a broker and reconciles the result.

    Reconciliation is the part that is easy to skip and expensive to omit. The
    broker's view of positions is authoritative; ours is a model of it. When
    they disagree — a partial fill we missed, a corporate action the broker
    applied — the platform must halt rather than continue trading against a
    fictional portfolio.
    """

    def place(self, order: OrderRequest) -> int: ...

    def cancel(self, order_id: int) -> None: ...

    def reconcile(self, portfolio_id: int) -> list[str]:
        """Return discrepancies between our state and the broker's.

        An empty list means agreement. A non-empty list must stop trading for
        that portfolio until resolved.
        """
        ...
